config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]
  delete 'charges/cancel_premium' => 'charges#cancel_premium', as: :cancel_premium

  resources :wikis
  devise_for :users

  get 'auto_sign' => 'welcome#auto_sign'
  get 'my_page' => 'user_page#view_user_page'

  root 'welcome#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  def self.default
    1_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  def self.make_collaborators(string, wiki_id)
    return Collaborator.none if string.empty?
    collabs = []
    @invalids = []

    string.split(",").map do |collaborator|
      if user = User.find_by(email: collaborator.strip)
        collabs << Collaborator.find_or_create_by(user_id: user.id, wiki_id: wiki_id)
      else
        @invalids << collaborator.strip
      end
    end
    collabs
  end

  def self.invalid_emails
    @invalids
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :init
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :wikis, through: :collaborators

  enum role: [:standard, :premium, :admin]

  def init
    self.role ||= :standard if self.has_attribute? :role
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :ordered_by_created_at, -> { order('created_at DESC') }
  scope :visible_to, -> (user) do
    if user.present? && (user.admin? || user.premium?)
      all
    else
      where(private: false)
    end
  end

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    wikis_path
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card:  params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer:    customer.id, # Note -- this is NOW the user_id in your app
      amount:      Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency:    'usd'
    )

    current_user.premium!
    flash[:notice] = "Upgraded to Premium successfully, #{current_user.email}! Feel free to create the private wikis!"
    redirect_to wikis_path

    # Stripe will send back CardErrors, with friendly messages
    # When something goes wrong.
    # This 'rescue block' catches and displays those errors.
    rescue Stripe::CardError => e
      flash.now[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key:         "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount:      Amount.default
    }
  end

  def cancel_premium
    current_user.standard!
    # current_user.wikis.each do |wiki|
    Wiki.where(user_id: current_user.id).each do |wiki|
      wiki.update_attribute(:private, false)
    end

    flash[:notice] = "You have canceled Premium servie, #{current_user.email}! You are now #{current_user.role} member and all your wikis are public now."
    redirect_to wikis_path
  end
end

app/controllers/user_page_controller.rb
class UserPageController < ApplicationController
  def view_user_page
    @user = User.find(params[:user])
    @public_wikis = Wiki.where(user: @user, private: false)
    @private_wikis = Wiki.where(user: @user, private: true)
    @collaborated_wikis = Wiki.where(id: Collaborator.where(user: @user).map(&:wiki_id))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end

  def auto_sign
    tester = User.find_by(email: "test@test.io")
    sign_in(tester)
    flash[:notice] = "You are signed in as test user."
    redirect_to root_path
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:show, :edit, :update, :destroy]
  before_action :owner_or_admin, only: :destroy

  # GET /wikis
  def index
    @wikis = policy_scope(Wiki)
  end

  # GET /wikis/1
  def show
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  def create
    @wiki = current_user.wikis.build(wiki_params)
    @wiki.user = current_user
    collabs = Collaborator.make_collaborators(params[:wiki][:collaborators], params[:wiki][:id])

    if @wiki.save && Collaborator.invalid_emails.blank?
      @wiki.collaborators = collabs
      redirect_to @wiki, notice: 'Wiki was successfully created.'
    else
      flash.now[:alert] = "Invalid emails: #{Collaborator.invalid_emails.map {|e| e }.join(', ')}" if Collaborator.invalid_emails.present?
      render :new
    end
  end

  # PATCH/PUT /wikis/1
  def update
    collabs = Collaborator.make_collaborators(params[:wiki][:collaborators], params[:wiki][:id])

    if @wiki.update(wiki_params) && Collaborator.invalid_emails.blank?
      @wiki.collaborators = collabs
      redirect_to @wiki, notice: 'Wiki was successfully updated.'
    else
      flash.now[:alert] = "Invalid emails: #{Collaborator.invalid_emails.map {|e| e }.join(', ')}" if Collaborator.invalid_emails.present?
      render :edit
    end
  end

  # DELETE /wikis/1
  def destroy
    if @wiki.destroy
      redirect_to wikis_url, notice: 'Wiki was successfully destroyed.'
    else
      flash[:alert] = "There was an error updating the wiki. Please try again."
      render :index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end

    def authorize_user
      if @wiki.private && !current_user # guest user
        flash[:alert] = "Please sign in to view wikis."
        redirect_to new_user_session_path
      elsif @wiki.private && current_user &&
        !(current_user == @wiki.user || @wiki.collaborators.pluck(:user_id).include?(current_user.id) || current_user.admin?)
        flash[:alert] = "This wiki's owner or its collaborators ONLY see this view."
        redirect_to wikis_path
      end
    end

    def owner_or_admin
      unless current_user == @wiki.user || current_user.admin?
        flash[:alert] = "Only this wiki's owner and an admin can do that."
        redirect_to wiki_path(@wiki)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/user_page_helper.rb
module UserPageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized?(wiki)
    current_user && (current_user == wiki.user || wiki.collaborators.pluck(:user_id).include?(current_user.id) || current_user.admin?)
  end

  def owner_or_admin(wiki)
    current_user == wiki.user || current_user && current_user.admin?
  end

  def markdown_wiki(text)
    options = {
      filter_html:         true,
      hard_wrap:           true,
      link_attributes:     { rel: "nofollow", target: "_blank" }
    }

    extensions = {
      space_after_headers:          true,
      autolink:                     true,
      superscript:                  true,
      disable_indented_code_blocks: true,
      fenced_code_blocks:           true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def display_collaborators(collaborators)
    raw collaborators.map {|c| link_to User.find(c.user_id).email, my_page_path(user: User.find(c.user_id)),  class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/views/charges/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="page-header">
      <h1 class="text-center">Premium</h1>
      <p class="pull-right">- share your information with the world</p>
      <br>
    </div>

    <div class="alert alert-danger">
      Currently the site is on test mode, genuine card can't be used. To learn more about test cards, click <a href="https://stripe.com/docs/testing#cards" target="_blank" class="btn btn-xs btn-info">here</a>.
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Why is Premium good?</h3>
          </div>
          <div class="panel-body">
            <ul style="list-style: none; padding-left: 0;">
              <li><span class="glyphicon glyphicon-ok"></span> It is easy and fast</li>
              <li><span class="glyphicon glyphicon-ok"></span> Creates priate wikis</li>
              <li><span class="glyphicon glyphicon-ok"></span> Lorem ipsum dolor sit</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <h4>Upgrade to Premium</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
        <% if current_user.standard? %>
          <%= form_tag charges_path, class: 'pull-right' do %>
            <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
          <% end %>
        <% else %>
          <div class="alert alert-warning" role="alert">
            You are already <%= current_user.role %>. You don't need to upgrade.
          </div>
          <%= link_to "Back to wikis", wikis_path, class: 'btn btn-primary pull-right' %>
        <% end %>
      </div>
    </div> <!-- /.row -->
    <br>
    <hr>
    <% if current_user.premium? %>
      <div class="row">
        <h4>Cancelation the premium service</h4>
        <p>If you cancel your premium service, all your private wikis will be public.</p>
        <%= link_to "Cancel Premium", cancel_premium_path, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: "If you cancel your premium service, all your private wikis will be public. Do you still want to proceed?" } %>
      </div> <!-- /.row -->
    <% end %>
  </div> <!-- /.col-md-6 col-md-offset-3 -->
</div> <!-- /.row -->
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <% if current_user.nil? || current_user.standard? %>
        <li><%= link_to "Premium", new_charge_path %></li>
      <% else %>
        <li><%= link_to "My Premium Settings", new_charge_path, id: 'change-premium-settings' %></li>
      <% end %>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          <strong><%= link_to current_user.email, my_page_path(user: current_user) %></strong> |
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'navbar-link'%>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link' %> |
          <%= link_to "Sign In", new_user_session_path, class: 'navbar-link' %>
        <% end %>
      </div>
    </ul>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/user_page/view_user_page.html.erb
<br>
<div class="container">
  <div class="jumbotron">
    <h3><%= @user.email %></h3>
    <p class="text-faded">This page shows all your wikis and wikis you collaborated with others.</p>
    <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-info' %>
    <a id="target-element" class="btn btn-primary" href="/wikis" role="button">Go to wiki list</a>
    <%= link_to "Write New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>

  <div class="row">
    <% if @user == current_user || current_user.admin? %>
      <div class="col-xs-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Public Wikis</h3>
          </div>
          <div class="panel-body">
            <% @public_wikis.each do |w| %>
              <p><%= link_to w.title, wiki_path(w) %></p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Private Wikis</h3>
          </div>
          <div class="panel-body">
            <% if @user.premium? %>
              <% @private_wikis.each do |w| %>
                <p><%= link_to w.title, wiki_path(w) %></p>
              <% end %>
            <% else %>
              <%= link_to "Upgrade membership", new_charge_path, class: 'btn btn-success btn-xs' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Collaborated Wikis</h3>
          </div>
          <div class="panel-body">
            <% @collaborated_wikis.each do |w| %>
              <p><%= link_to w.title, wiki_path(w) %></p>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Public Wikis</h3>
          </div>
          <div class="panel-body">
            <% @public_wikis.each do |w| %>
              <p><%= link_to w.title, wiki_path(w) %></p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Collaborated Wikis</h3>
          </div>
          <div class="panel-body">
            <% @collaborated_wikis.each do |w| %>
              <p><%= link_to w.title, wiki_path(w) if !w.private || @user == current_user %></p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h2>Wiki App</h2>
  <p>Wiki app is a production quality SaaS app that allows users to create their own wikis. Users can create public and private Markdown-based wikis.</p>

  <p>Wikis are a great way to collaborate on community-sourced content. Whether the wiki is for a hobby or work-related project, users can create their own wikis and share them publicly or privately with other collaborators.</p>
  <a href="https://github.com/ghbooth12/wiki_app" target="_blank" class="btn btn-info">GitHub</a>
  <a id="target-element" class="btn btn-primary" href="/wikis" role="button">See wikis</a>
  <%= link_to "Sign in as test user", auto_sign_path, class: 'btn btn-success' %>
</div>

<div id="steps" class="row">
  <div class="col-xs-12">
    <div class="panel">
      <div class="panel-heading">
        <h2><strong>How it works</strong></h2>
        <p>Log-in as test user account, take a look how it works.</p>
      </div>
      <div class="panel-body">
        <div class="well">
          <ol class="hover-link">
            <li>
              Log in as test user automatically. <%= link_to "Click here", auto_sign_path, class: 'btn btn-xs btn-success' %>
            </li>
            <li>
              <%= link_to wikis_path do %>
                Go to Wiki index page. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to new_wiki_path do %>
                Create a new wiki. It supports Markdown syntax.(Hover around bottom right, you will see the preview of your wiki.) <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to new_wiki_path do %>
                Add collaborators of the new wiki in the form. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to my_page_path(user: User.find_by(email: "test@test.io")) do %>
                See user profile. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
          </ol>

          <h4>For Premium User</h4>
          <p>Test User is already a premium level for demonstration.</p>
          <ul class="hover-link">
            <li>
              <%= link_to new_charge_path do %>
                Upgrade membership by paying just $1. The premium membership can be canceled at any time. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to wikis_path do %>
                Premium users can have private wikis.(Even if the wiki is collaborated with standard users.) <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
          </ul>
        </div> <!-- .well -->
      </div> <!-- .panel-body -->
    </div> <!-- .panel -->
  </div> <!-- .col-xs-12 -->
</div> <!-- .row -->

app/views/wikis/_form.html.erb
<%= form_for @wiki, html: { class: "wiki_form" } do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h4>
      <ul>
        <% @wiki.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: 'sr-only' %><br>
    <%= f.text_field :title, autofocus: true, placeholder: 'Type your title here', class: 'form-control' %>
  </div>
  <!-- Body: <%#= f.object.body %> -->
  <div class="field form-group">
    <%= f.label :body, class: 'sr-only' %><br>
    <div id="epiceditor">
      <%= f.text_area :body, rows: 7, placeholder: 'Share what you know.', class: 'form-control' %>
    </div>
  </div>

  <% if current_user.premium? || current_user.admin? %>
    <div class="checkbox">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :collaborators %><br>
    <%= f.text_field :collaborators, placeholder: 'Type collaborators (separated by commas)', value: @wiki.collaborators.map{|c| User.find(c.user_id).email }.join(', '), class: 'form-control' %>
  </div>

  <div class="actions form-group pull-right">
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <span class="glyphicon glyphicon-ok-circle"></span> Save Wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="page-header">
      <h1 class="text-center">Edit the Wiki</h1>
      <p class="pull-right">- share your information with the world</p>
      <br>
    </div>

    <%= render 'form' %>

    <%= link_to 'Back to list', wikis_path, class: 'btn btn-default'  %>
  </div>
</div>

<script type="text/javascript">
  var editor = new EpicEditor().load();
</script>

app/views/wikis/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1 class="text-center">Wikis</h1>
      <p class="pull-right">- share your information with the world</p>
      <br>
    </div>
    <p class="text-faded text-center">List of public wikis. For premium members private wikis are listed as well.</p>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Wiki Type</th>
          <th>Title(number of collaborators)</th>
          <th>User</th>
          <th>Created At</th>
          <% if current_user %>
            <th colspan="2">Manage</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @wikis.each do |wiki| %>
          <tr>
            <% if wiki.private %>
              <td><span class="glyphicon glyphicon-lock"></span></td>
            <% else %>
              <td><span class="glyphicon glyphicon-globe"></span></td>
            <% end %>
            <td><span class="badge"><%= wiki.collaborators.count %></span> <%= link_to truncate(wiki.title), wiki %></td>
            <td><%= link_to wiki.user.email, my_page_path(user: wiki.user) %></td>
            <td><%= wiki.created_at.strftime("%F %T") %></td>
            <% if user_is_authorized?(wiki) %>
              <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
            <% end %>
            <% if owner_or_admin(wiki) %>
              <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure you want to delete this wiki?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>

    <small><span class="glyphicon glyphicon-globe"></span> public wiki | <span class="glyphicon glyphicon-lock"></span> private wiki |
    <span class="badge">#</span> number of collaborators</small>
    <% if current_user %>
      <%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>
<br><br>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="page-header">
      <h1 class="text-center">Compose new Wiki</h1>
      <p class="pull-right">- share your information with the world</p>
      <br>
    </div>

    <%= render 'form' %>

    <%= link_to 'Back to list', wikis_path, class: 'btn btn-default' %>
  </div>
</div>

<script type="text/javascript">
  var editor = new EpicEditor().load();
  // To make 'edit box' empty on the wiki 'new' page
  // Without this code, epiceditor holds onto a previous content
  editor.getElement('editor').body.innerHTML='';
</script>

app/views/wikis/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="page-header">
      <h1 class="text-center">My Wikis List</h1>
      <p class="pull-right">- share your information with the world</p>
      <br>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @wiki.title %></h3>
      </div>
      <div class="panel-body">
        <%= markdown_wiki(@wiki.body) %>
        <hr>
        <% if @wiki.private %>
          <span class="glyphicon glyphicon-lock"></span> private wiki
        <% else %>
          <span class="glyphicon glyphicon-globe"></span> public wiki
        <% end %>

        <div class="pull-right">
          updated on <%= @wiki.updated_at.strftime("%F") %> |
          created on <%= @wiki.created_at.strftime("%F") %> by <%= link_to @wiki.user.email, my_page_path(user: @wiki.user) %>
        </div>
      </div>
      <div class="panel-footer">
        <small>Collaborators</small>
        <%= display_collaborators(@wiki.collaborators) %>
      </div>
    </div>

    <%= link_to 'Back to list', wikis_path, class: 'btn btn-default' %>

    <% if user_is_authorized?(@wiki) %>
      <div class="pull-right">
        <%= link_to 'Edit', edit_wiki_path(@wiki), class: 'btn btn-primary' %>
    <% end %>
    <% if owner_or_admin(@wiki) %>
        <%= link_to 'Delete', @wiki, method: :delete, class: 'btn btn-warning', data: { confirm: "Are you sure you want to delete this wiki?" } %>
      </div>
    <% end %>
  </div>
</div>